version: '3.3'

services:
  drupal:
    build: ./docker/drupal/
    container_name: drupal-10-blog
    ports:
      - 8080:80
    volumes:
      - ./src:/opt
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini

  database:
    build: ./docker/db/
    image: postgres:15.3
    container_name: drupal-10-blog-db
    ports:
      - 5442:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=drupal-10-blog-db
    volumes:
      - drupal-10-blog-db:/var/lib/postgresql/data

volumes:
  drupal-10-blog-db:
